# ref: https://github.com/Sving1024/PKGBUILD/blob/main/.github/workflows/publish_to_aur.yml
name: Publish packages to AUR
on:
  push:
  workflow_dispatch:

jobs:
  publish_to_aur_accesser:
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        repo: [v2rayn-bin]
    name: publish to aur
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cat PKGBUILD
        run: cat ${{matrix.repo}}/PKGBUILD
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          pkgname: ${{matrix.repo}}
          test: false
          updpkgsums: false
          commit_username: "github-actions[bot]"
          commit_email: "xihale.top@qq.com" # "41898282+github-actions[bot]@users.noreply.github.com"
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "git actions auto update"
          allow_empty_commits: false
          pkgbuild: ${{matrix.repo}}/PKGBUILD
          assets: |
            ${{matrix.repo}}/v2rayN-bin.desktop
            ${{matrix.repo}}/v2rayN.png
