name: v2rayn-bin

on:
  schedule:
    - cron: 0 0 * * * # 每天凌晨0点运行一次
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest version
        id: get-latest-version
        run: |
          echo "Fetching the latest version from GitHub releases..."
          RELEASE_INFO=$(curl -s https://api.github.com/repos/2dust/v2rayN/releases/latest)
          LATEST_VERSION=$(echo "$RELEASE_INFO" | grep '"tag_name":' | cut -d '"' -f 4)
          echo "Latest version fetched: $LATEST_VERSION"
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Check if update is needed
        id: check-update
        run: |
          echo "Checking if update is needed..."
          AUR_INFO=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=v2rayn-bin")
          CURRENT_VERSION=$(echo "$AUR_INFO" | jq -r '.results[0].Version' | cut -d '-' -f 1)
          echo "Current version: $CURRENT_VERSION"
          echo "Latest version: ${{ steps.get-latest-version.outputs.latest_version }}"
          if [ "$CURRENT_VERSION" == "${{ steps.get-latest-version.outputs.latest_version }}" ]; then
            echo "Update is not needed."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Update is needed."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      skip: ${{ steps.check-update.outputs.skip }}
      latest_version: ${{ steps.get-latest-version.outputs.latest_version }}

  update-and-publish:
    runs-on: ubuntu-latest
    needs: check-update
    if: ${{ needs.check-update.outputs.skip != 'true' }}
    steps:
      - name: Checkout code
        run: |
          echo "Cloning AUR repository..."
          git clone https://aur.archlinux.org/v2rayn-bin.git --depth=1 v2rayn-bin

      - name: Update PKGBUILD
        run: |
          echo "Updating PKGBUILD to version ${{ needs.check-update.outputs.latest_version }}..."
          cd v2rayn-bin
          sed -i "s/^pkgver=.*/pkgver=${{ needs.check-update.outputs.latest_version }}/" PKGBUILD
          echo "PKGBUILD updated."

      - name: Generate sha256sums
        run: |
          echo "Generating sha256sums..."
          cd v2rayn-bin
          X86_64_URL="https://github.com/2dust/v2rayN/releases/download/${{ needs.check-update.outputs.latest_version }}/v2rayN-linux-64.zip"
          wget -q "$X86_64_URL"
          X86_64_SHA256SUM=$(sha256sum v2rayN-linux-64.zip | cut -d ' ' -f 1)
          echo "X86_64_SHA256SUM=$X86_64_SHA256SUM"
          ARM64_URL="https://github.com/2dust/v2rayN/releases/download/${{ needs.check-update.outputs.latest_version }}/v2rayN-linux-arm64.zip"
          wget -q "$ARM64_URL"
          ARM64_SHA256SUM=$(sha256sum v2rayN-linux-arm64.zip | cut -d ' ' -f 1)
          echo "ARM64_SHA256SUM=$ARM64_SHA256SUM"
          sed -i "s/^sha256sums_x86_64=.*/sha256sums_x86_64=($X86_64_SHA256SUM)/" PKGBUILD
          sed -i "s/^sha256sums_arm64=.*/sha256sums_arm64=($ARM64_SHA256SUM)/" PKGBUILD
          echo "sha256sums generated and updated in PKGBUILD."

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          pkgname: v2rayn-bin
          commit_username: "github-actions[bot]"
          commit_email: "github-actions[bot]@users.noreply.github.com"
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "release ${{ needs.check-update.outputs.latest_version }}"
          allow_empty_commits: false
          pkgbuild: v2rayn-bin/PKGBUILD
          assets: |
            v2rayn-bin/v2rayN-bin.desktop
            v2rayn-bin/v2rayN.png